'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { 
  CodeBracketIcon,
  CheckCircleIcon,
  ClockIcon,
  DocumentTextIcon,
  ArrowTopRightOnSquareIcon
} from '@heroicons/react/24/outline'

interface GeneratedFix {
  id: string
  issueId: string
  title: string
  description: string
  filesModified: string[]
  linesChanged: number
  confidence: number
  testsCovered: number
  status: 'generating' | 'completed' | 'testing' | 'deployed'
  generatedAt: Date
  codePreview: string
  commitMessage: string
}

const mockFixes: GeneratedFix[] = [
  {
    id: 'fix-001',
    issueId: 'issue-001',
    title: 'Database Connection Pool Fix',
    description: 'Implemented connection pool optimization and circuit breaker pattern for payment service',
    filesModified: ['src/services/payment.ts', 'src/config/database.ts', 'tests/payment.test.ts'],
    linesChanged: 47,
    confidence: 0.91,
    testsCovered: 12,
    status: 'completed',
    generatedAt: new Date(Date.now() - 3 * 60 * 1000),
    codePreview: `// Enhanced connection pool with circuit breaker
class DatabasePool {
  private circuitBreaker: CircuitBreaker;
  
  constructor() {
    this.circuitBreaker = new CircuitBreaker({
      timeout: 5000,
      errorThreshold: 5,
      resetTimeout: 30000
    });
  }
  
  async getConnection(): Promise<Connection> {
    return this.circuitBreaker.execute(async () => {
      return await this.pool.getConnection();
    });
  }
}`,
    commitMessage: '🤖 Fix: Implement circuit breaker for database connections\n\nResolves timeout issues in payment service by adding:\n- Connection pool optimization\n- Circuit breaker pattern\n- Enhanced error handling\n\nGenerated by Cline CLI\nConfidence: 91%'
  },
  {
    id: 'fix-002',
    issueId: 'issue-002',
    title: 'Redis Connection Leak Fix',
    description: 'Updated Redis client library and implemented proper connection cleanup',
    filesModified: ['src/services/auth.ts', 'package.json'],
    linesChanged: 23,
    confidence: 0.84,
    testsCovered: 8,
    status: 'testing',
    generatedAt: new Date(Date.now() - 8 * 60 * 1000),
    codePreview: `// Proper Redis connection management
class AuthService {
  private redis: Redis;
  
  constructor() {
    this.redis = new Redis({
      host: process.env.REDIS_HOST,
      lazyConnect: true,
      maxRetriesPerRequest: 3
    });
  }
  
  async cleanup(): Promise<void> {
    await this.redis.disconnect();
  }
}`,
    commitMessage: '🤖 Fix: Resolve Redis connection leak in auth service\n\nUpdates:\n- Redis client to v5.0.1\n- Proper connection cleanup\n- Lazy connection initialization\n\nGenerated by Cline CLI\nConfidence: 84%'
  },
  {
    id: 'fix-003',
    issueId: 'issue-003',
    title: 'API Rate Limiting Implementation',
    description: 'Added exponential backoff and request queuing for external API calls',
    filesModified: ['src/services/notification.ts', 'src/utils/rateLimiter.ts'],
    linesChanged: 35,
    confidence: 0.76,
    testsCovered: 6,
    status: 'generating',
    generatedAt: new Date(Date.now() - 1 * 60 * 1000),
    codePreview: `// Exponential backoff rate limiter
class RateLimiter {
  private queue: RequestQueue;
  private backoffMultiplier = 2;
  
  async execute<T>(fn: () => Promise<T>): Promise<T> {
    return this.queue.add(async () => {
      try {
        return await fn();
      } catch (error) {
        if (error.status === 429) {
          await this.exponentialBackoff();
          throw error;
        }
      }
    });
  }
}`,
    commitMessage: '🤖 Fix: Implement rate limiting for external APIs\n\nAdds:\n- Exponential backoff mechanism\n- Request queuing system\n- 429 error handling\n\nGenerated by Cline CLI\nConfidence: 76%'
  }
]

const statusColors = {
  generating: 'bg-blue-500/10 text-blue-400 border border-blue-500/20',
  completed: 'bg-green-500/10 text-green-400 border border-green-500/20',
  testing: 'bg-orange-500/10 text-orange-400 border border-orange-500/20',
  deployed: 'bg-green-500/20 text-green-300 border border-green-500/30'
}

const statusIcons = {
  generating: ClockIcon,
  completed: CheckCircleIcon,
  testing: DocumentTextIcon,
  deployed: ArrowTopRightOnSquareIcon
}

export default function FixesGenerated() {
  const [selectedFix, setSelectedFix] = useState<GeneratedFix | null>(null)
  const [showCode, setShowCode] = useState<string | null>(null)

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 0.9) return 'text-green-400'
    if (confidence >= 0.8) return 'text-blue-400'
    if (confidence >= 0.7) return 'text-orange-400'
    return 'text-red-400'
  }

  return (
    <div className="space-y-4">
      {/* Summary Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-3">
          <div className="flex items-center space-x-2">
            <CodeBracketIcon className="w-5 h-5 text-blue-500" />
            <div>
              <div className="text-lg font-semibold text-white">
                {mockFixes.length}
              </div>
              <div className="text-xs text-gray-400">
                Fixes Generated
              </div>
            </div>
          </div>
        </div>

        <div className="bg-green-500/10 border border-green-500/20 rounded-lg p-3">
          <div className="flex items-center space-x-2">
            <CheckCircleIcon className="w-5 h-5 text-green-500" />
            <div>
              <div className="text-lg font-semibold text-white">
                {mockFixes.filter(f => f.status === 'completed' || f.status === 'deployed').length}
              </div>
              <div className="text-xs text-gray-400">
                Completed
              </div>
            </div>
          </div>
        </div>

        <div className="bg-purple-500/10 border border-purple-500/20 rounded-lg p-3">
          <div className="flex items-center space-x-2">
            <DocumentTextIcon className="w-5 h-5 text-purple-500" />
            <div>
              <div className="text-lg font-semibold text-white">
                {mockFixes.reduce((acc, f) => acc + f.linesChanged, 0)}
              </div>
              <div className="text-xs text-gray-400">
                Lines Changed
              </div>
            </div>
          </div>
        </div>

        <div className="bg-indigo-500/10 border border-indigo-500/20 rounded-lg p-3">
          <div className="flex items-center space-x-2">
            <CheckCircleIcon className="w-5 h-5 text-indigo-500" />
            <div>
              <div className="text-lg font-semibold text-white">
                {mockFixes.reduce((acc, f) => acc + f.testsCovered, 0)}
              </div>
              <div className="text-xs text-gray-400">
                Tests Created
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Fixes List */}
      <div className="space-y-3">
        {mockFixes.map((fix, index) => {
          const StatusIcon = statusIcons[fix.status]
          
          return (
            <motion.div
              key={fix.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
              className={`p-4 rounded-lg border-2 cursor-pointer transition-all duration-200 ${
                selectedFix?.id === fix.id 
                  ? 'border-blue-500/50 bg-blue-500/5' 
                  : 'border-gray-800 bg-gray-900/30 hover:border-gray-700'
              }`}
              onClick={() => setSelectedFix(selectedFix?.id === fix.id ? null : fix)}
            >
              <div className="flex items-start justify-between">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center space-x-3 mb-2">
                    <StatusIcon className="w-5 h-5 text-gray-400" />
                    <h3 className="text-sm font-medium text-white truncate">
                      {fix.title}
                    </h3>
                    <span className={`badge ${statusColors[fix.status]}`}>
                      {fix.status}
                    </span>
                    <div className="flex items-center space-x-1">
                      <CodeBracketIcon className="w-3 h-3 text-gray-500" />
                      <span className="text-xs text-gray-500">
                        Cline CLI
                      </span>
                    </div>
                  </div>
                  
                  <p className="text-sm text-gray-400 mb-2">
                    {fix.description}
                  </p>
                  
                  <div className="flex items-center space-x-4 text-xs text-gray-500">
                    <span>{fix.filesModified.length} files</span>
                    <span>{fix.linesChanged} lines</span>
                    <span className={getConfidenceColor(fix.confidence)}>
                      {(fix.confidence * 100).toFixed(1)}% confidence
                    </span>
                    <span>{fix.generatedAt.toLocaleTimeString()}</span>
                  </div>
                </div>
              </div>

              {/* Expanded Details */}
              {selectedFix?.id === fix.id && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className="mt-4 pt-4 border-t border-gray-800"
                >
                  <div className="space-y-4">
                    {/* Files Modified */}
                    <div>
                      <h4 className="text-sm font-medium text-white mb-2">
                        Files Modified
                      </h4>
                      <div className="space-y-1">
                        {fix.filesModified.map(file => (
                          <div key={file} className="flex items-center space-x-2">
                            <DocumentTextIcon className="w-4 h-4 text-gray-500" />
                            <span className="text-sm font-mono text-gray-300">
                              {file}
                            </span>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Code Preview */}
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <h4 className="text-sm font-medium text-gray-900 dark:text-white">
                          Generated Code Preview
                        </h4>
                        <button
                          onClick={() => setShowCode(showCode === fix.id ? null : fix.id)}
                          className="text-xs text-secondary-600 hover:text-secondary-700"
                        >
                          {showCode === fix.id ? 'Hide' : 'Show'} Code
                        </button>
                      </div>
                      
                      {showCode === fix.id && (
                        <motion.div
                          initial={{ opacity: 0, height: 0 }}
                          animate={{ opacity: 1, height: 'auto' }}
                          className="bg-black rounded-lg p-4 overflow-x-auto border border-gray-800"
                        >
                          <pre className="text-sm text-gray-200">
                            <code>{fix.codePreview}</code>
                          </pre>
                        </motion.div>
                      )}
                    </div>

                    {/* Commit Message */}
                    <div>
                      <h4 className="text-sm font-medium text-white mb-2">
                        Commit Message
                      </h4>
                      <div className="bg-gray-900 rounded-lg p-3 border border-gray-800">
                        <pre className="text-sm text-gray-300 whitespace-pre-wrap">
                          {fix.commitMessage}
                        </pre>
                      </div>
                    </div>

                    {/* Actions */}
                    <div className="flex items-center justify-between pt-2">
                      <div className="flex space-x-2">
                        {fix.status === 'completed' && (
                          <>
                            <button className="btn btn-primary btn-sm">
                              Create PR
                            </button>
                            <button className="btn btn-secondary btn-sm">
                              Run Tests
                            </button>
                          </>
                        )}
                        {fix.status === 'testing' && (
                          <button className="btn btn-warning btn-sm">
                            View Test Results
                          </button>
                        )}
                        <button className="btn btn-outline btn-sm">
                          View Diff
                        </button>
                      </div>
                      
                      <div className="text-xs text-gray-500">
                        Fix ID: {fix.id}
                      </div>
                    </div>
                  </div>
                </motion.div>
              )}
            </motion.div>
          )
        })}
      </div>

      {/* Cline CLI Status */}
      <div className="bg-gradient-to-r from-blue-500/10 to-purple-500/10 border border-blue-500/20 rounded-lg p-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-3 h-3 bg-green-500 rounded-full animate-pulse glow-green" />
            <span className="text-sm font-medium text-white">
              Cline CLI Active
            </span>
            <span className="text-xs text-gray-400">
              Model: claude-3-sonnet-20240229
            </span>
          </div>
          <div className="text-sm text-gray-400">
            Next generation ready
          </div>
        </div>
      </div>
    </div>
  )
}
